### ISSUE TITLE
chapter1_myMap wont run on linux

### ISSUE THREAD

**Issue by Krisselack** [PacktPublishing/QGIS-Python-Programming-Cookbook-Second-Edition#2]
I cannot run this on Ubuntu 18.04; QGIS 2.18
I tried to change the path to /usr/bin/qgis, probably wrong. 
Not really an idea hwo to fix this. 

Error: 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 196, in qgis_excepthook
    showException(type, value, tb, None, messagebar=True)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 107, in showException
    open_stack_dialog(type, value, tb, msg)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 142, in open_stack_dialog
    iface.messageBar().popWidget()
AttributeError: 'NoneType' object has no attribute 'messageBar'

Original exception was:
Traceback (most recent call last):
  File "/home/abc/wd/pygis/MyMap/myMap.py", line 23, in <module>
    pr.addFeatures([linstr])
AttributeError: 'NoneType' object has no attribute 'addFeatures'

`# Standalone QGIS script
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from PyQt4.QtCore import *
from PyQt4.QtGui import *

app = QgsApplication([], True)
path = "/usr/bin/qgis"
app.setPrefixPath(path, True)
app.initQgis()
canvas = QgsMapCanvas()
title = "PyQGIS Standalone Application Example"
canvas.setWindowTitle(title)
canvas.setCanvasColor(Qt.white)
layer_info = 'LineString?crs=epsg:4326'
layer =  QgsVectorLayer(layer_info, 'MyLine' , "memory")
pr = layer.dataProvider()
linstr = QgsFeature()
wkt = "LINESTRING (1 1, 10 15, 40 35)"
geom = QgsGeometry.fromWkt(wkt)
linstr.setGeometry(geom)
pr.addFeatures([linstr])
layer.updateExtents()
QgsMapLayerRegistry.instance().addMapLayer(layer)
canvas.setExtent(layer.extent())
canvas.setLayerSet([QgsMapCanvasLayer(layer)])
canvas.zoomToFullExtent()
canvas.show()
exitcode = app.exec_()
QgsApplication.exitQgis()
sys.exit(exitcode)`

**Comment by Krisselack** [comment]
Nevermind, I "solved" it. 
Path was set as: path = "/usr" after runnint QgsApplication.prefixPath() in the qgis-python-console.
